# docker run -ti  --security-opt apparmor:unconfined sec-vault

security-vault:
  image: 894431722748.dkr.ecr.us-east-1.amazonaws.com/security-vault:VERSION
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/tmp/vaultprueba:/tmp"
  environment:
    - VAULT_SERVER=http://vault-server:8200
    - ROLE=cloudframe-dot-wtf
    - TOKEN_PATH=/etc/token
    - SECRET_PATH=/tmp
    - PERSISTENCE_PATH=/tmp/
  labels:
    service: security-vault

dummy:
  image: alpine:latest
  command: [ "true" ]
  labels:
    - io.rancher.container.start_once=true
    - io.rancher.scheduler.affinity:container_label=service=security-vault

security-vault-at:
  image: 894431722748.dkr.ecr.us-east-1.amazonaws.com/security-vault-at:VERSION
  links:
    - security-vault
  depends_on:
    - security-vault
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  labels:
    - io.rancher.container.start_once=true
    - io.rancher.scheduler.affinity:container_label=service=security-vault

vault-server:
  image: vault:0.6.2
  environment:
    - VAULT_DEV_ROOT_TOKEN_ID=ffe5c779-f23c-beac-7228-9a600a23b73f
  labels:
    - io.rancher.scheduler.affinity:container_label=service=security-vault

vault-configurator:
  image: 894431722748.dkr.ecr.us-east-1.amazonaws.com/vault-configurator:VERSION
  environment:
    - VAULT_DEV_ROOT_TOKEN_ID=ffe5c779-f23c-beac-7228-9a600a23b73f
  depends_on:
    - vault-server
  labels:
    - io.rancher.container.start_once=true
    - io.rancher.scheduler.affinity:container_label=service=security-vault

