# docker run -ti --security-opt apparmor:unconfined sec-vault

security-vault:
  image: 894431722748.dkr.ecr.us-east-1.amazonaws.com/security-vault:VERSION
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  labels:
    service: vault-volumedriver
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: domain=accounting,instance.size=medium